### ISSUE TITLE
Some issues on the up-sizing of the sd-card

### ISSUE THREAD

**Issue by CAnMove** [jbrzusto/sensorgnome-pi#3]
The Adafruit GPS HAT seems up and running (see below).

Since I am working from a Windows environment, I use Putty to SSH into the RPi2b. log in with pi/raspberry and then 'sudu su' to root. Otherwise from that, I can follow the instructions you gave. The partitions of my 16GB card looks like:

NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
mmcblk0     179:0    0 14.9G  0 disk
ââmmcblk0p1 179:1    0   60M  0 part /boot
ââmmcblk0p2 179:2    0  3.5G  0 part /
ââmmcblk0p3 179:3    0 11.3G  0 part /media/bigspace

but the SG reports 4GB of space:

"I am your SensorGnome

My machine ID is C519RPI289C6. 
I'm running the Thu, 23 Feb 2017 12:59:15 GMT software release. 
I have restarted 21 times since the last software update. 
I have been running for 0 days, 0 hours, and 5 minutes since the last restart.

I am located at   55.7146° N     13.208° E     110 m elev.  Update GPS fix

My clock says it is   2017-02-23 16:05:43.465 UTC clock not yet set by GPS PPS present

What I'm doing now:

Devices 
Internal: micro SD card with size = 4GB; Used = 27%
Directly Attached:   Adafruit GPS hat with PPS"

... so GPS OK, and also GPS HAT, but internal_sd_card gets infront of bigspace anyway. I will continue with multiple FunCubes tomorrow. BTW, could be a good idea to point out that you need a USB A male to female cable for the dongles. They are too thick to plug in more than one.

**Comment by jbrzusto** [comment]
The web interface isn't reporting storage on the bigspace partition, but it might be using it
anyway.  Maybe check where current files are being created...

**Comment by CAnMove** [comment]
Yep, seems to save SG data on bigspace, although not indicated on the 
web page.

/Arne


Den 2017-02-23 kl. 17:55, skrev John Brzustowski:

**Comment by jbrzusto** [comment]
Closed in deference to #5
